apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.fullname" . }}-collector
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 1010
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
    component: collector
