# apiVersion: monitoring.coreos.com/v1
# kind: Probe
# metadata:
#   name: {{ include "explorer.fullname" . }}
#   labels:
#     release: {{ .Values.kubePrometheusStack.release }}
# spec:
#   prober:
#     url: {{ .Values.kubePrometheusStack.blackboxURL }}
#   jobName: {{ include "explorer.fullname" . }}
#   targets:
#     staticConfig:
#       labels:
#         namespace: default
#       static:
#         - https://{{ .Values.apiServer.ingress.domain }}/healthz
