apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: miners
    release: prometheus
  name: miners-servicemonitor
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: miner
  endpoints:
      - interval: 15s
      - port: grpcport

