apiVersion: v2
name: spacemesh-api
version: 0.1.17
appVersion: v0.1.17
description: Spacemesh public API service
home: https://spacemesh.io
icon: https://avatars3.githubusercontent.com/u/33087498?s=200&v=4
type: application
dependencies:
  - name: ingress-nginx
    version: ~3.15.2
    repository: https://kubernetes.github.io/ingress-nginx
keywords:
  - spacemesh
  - blockchain
maintainers:
  - email: info@spacemesh.io
    name: Spacemesh Team
