datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

grafana.ini:
  server:
    root_url: https://ws-grafana.spacemesh.io
  auth.github:
    enabled: true
    client_id: <ID>
    client_secret: <SECRET>
    scopes: user:email,read:org
    allowed_organizations: spacemesh
  log:
    level: debug
