apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ include "spacemesh-dash.fullname" . }}
  labels:
    release: {{ .Values.kubePrometheusStack.release }}
spec:
  module: websocket
  interval: 120s
  scrapeTimeout: 70s
  prober:
    url: {{ .Values.kubePrometheusStack.blackboxURL }}
  jobName: {{ include "spacemesh-dash.fullname" . }}
  targets:
    staticConfig:
      labels:
        namespace: default
      static:
        - https://{{ .Values.ingress.domain }}/ws
