apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spacemesh-api.fullname" . }}
  labels:
    {{- include "spacemesh-api.labels" . | nindent 4 }}
data:
  config.json: |
{{ required "'config' must be specified" .Values.config | indent 4 }}