{{- $netID := required "netID must be specified" .Values.netID -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spacemesh-api.fullname" . }}
  labels:
    {{- include "spacemesh-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "spacemesh-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "1010"
      labels:
        {{- include "spacemesh-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "spacemesh-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: node
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/go-spacemesh"]
          args:
            - "--config"
            - "/etc/spacemesh/config.json"
            - "--json-server-new"
            - "--metrics"
          ports:
            - name: grpc
              containerPort: 9092
              protocol: TCP
            - name: json-rpc
              containerPort: 9093
              protocol: TCP
            - name: metrics
              containerPort: 1010
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9093
          startupProbe:
            tcpSocket:
              port: 9093
            failureThreshold: 120
          volumeMounts:
            - name: config
              mountPath: /etc/spacemesh
            - name: config
              mountPath: /root/spacemesh/{{ $netID }}/p2p/peers.json
              subPath: peers.json
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

        - name: check-sync
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: blacktop/httpie
          command: ["/bin/sh"]
          args: ["-c", "while sleep 100d; do :; done"]
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "set -e; set -o pipefail; echo '' | http localhost:9093/v1/node/status | jq -e .status.is_synced"]
      volumes:
        - name: config
          configMap:
            name: {{ include "spacemesh-api.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
