{{- if and .Values.ingress.enabled .Values.ingress.grpcDomain -}}
{{- $fullName := include "spacemesh-api.fullname" . -}}
{{- $domain := .Values.ingress.grpcDomain -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "spacemesh-api.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.controller }}
    {{- if eq .Values.ingress.controller "nginx" }}
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- end }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    nginx.ingress.kubernetes.io/server-snippet: |
      grpc_read_timeout 600s;
      grpc_send_timeout 600s;
      client_body_timeout 600s;
spec:
  tls:
    - hosts:
        - {{ $domain }}
      secretName: tls
  rules:
    - host: {{ $domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: 9092
{{- end }}
