apiVersion: v2
name: spacemesh-dash
version: 0.1.4
appVersion: v0.0.2
description: Spacemesh Dashboard
home: https://dash.spacemesh.io
icon: https://avatars3.githubusercontent.com/u/33087498?s=200&v=4
type: application
keywords:
  - spacemesh
  - blockchain
maintainers:
  - email: info@spacemesh.io
    name: Spacemesh Team
