apiVersion: v2
name: spacemesh-explorer
version: 0.1.7
appVersion: v0.0.1
description: Spacemesh Explorer
home: https://explorer.spacemesh.io
icon: https://avatars3.githubusercontent.com/u/33087498?s=200&v=4
type: application
keywords:
  - spacemesh
  - blockchain
maintainers:
  - email: info@spacemesh.io
    name: Spacemesh Team
